export const cats = [
  {
    with: 'с фуа-гра',
    size: '0,5',
    portions: 10,
    mouse: 'мышь в подарок',
    description: 'Сказочное заморское яство',
    question: 'Котэ не одобряет?',
    footer: 'Печень утки разварная с артишоками.',
    disabled: false,
  },
  {
    with: 'с рыбой',
    size: '2',
    portions: 40,
    quantity: 2,
    mouse: 'мыши в подарок',
    description: 'Сказочное заморское яство',
    question: 'Котэ не одобряет?',
    footer: 'Головы щучьи с чесноком да свежайшая сёмгушка.',
    disabled: false,
  },
  {
    with: 'с курой',
    size: '5',
    portions: 100,
    quantity: 5,
    mouse: `мышей в подарок заказчик доволен`,
    description: 'Сказочное заморское яство',
    question: 'Котэ не одобряет?',
    footer: 'Филе из цыплят с трюфелями в бульоне.',
    disabled: true,
  },
];
